# Leave fields blank to omit them from the manifest

iiif_server:
  host: iiif.bc.edu
  path:
  protocol: https
manifest_server:
  host: library.bc.edu
  protocol: https
  path: /iiif/manifests
image_filetype: jp2
namespaces:
  marc: 'http://www.loc.gov/MARC21/slim'
  premis: 'http://www.loc.gov/standards/premis'
de_fields:
  control: 'xb:digital_entity_call/xb:digital_entity/control'
  desc_md: 'xb:digital_entity_call/xb:digital_entity/mds/md[type="marc"]/value'
  preservation_md: 'xb:digital_entity_call/xb:digital_entity/mds/md[type="preservation_md"]/value'
  stream_ref: 'xb:digital_entity_call/xb:digital_entity/stream_ref'
marc_fields:
  access_condition: 'marc:record/marc:datafield[@tag="540"]/marc:subfield[@code="a"]'
  local_collection: 'marc:record/marc:datafield[@tag="940"]/marc:subfield[@code="a"]'
  owner: 'marc:record/marc:datafield[@tag="533"]/marc:subfield[@code="c"]'